(function(){
const URL="https://script.google.com/macros/s/AKfycbxGFddUtzm9z2vfnp2TRtrgAExzRsoIA6BLzKwhppOyOKR3TfCsHwrypgIOqBGLmIC_LA/exec",S={data:[],dosen:[],loaded:false},$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),txt=v=>String(v??"").trim();
function status(m,e){$("msg").textContent=m||"";$("msg").style.color=e?"#b32d2e":"#27613d"}
function jsonp(params){return new Promise((ok,no)=>{let cb="pm"+Date.now()+Math.random().toString(16).slice(2),s=document.createElement("script"),t=setTimeout(()=>done(new Error("Koneksi timeout")),15000);function done(e,d){clearTimeout(t);delete window[cb];s.remove();e?no(e):ok(d)}window[cb]=d=>done(null,d);params.callback=cb;s.src=URL+"?"+new URLSearchParams(params);s.onerror=()=>done(new Error("Gagal menghubungi Apps Script"));document.head.appendChild(s)})}
async function loadDosen(){if(S.dosen.length)return;let r=await jsonp({action:"getDosen"});if(r.result!=="success")throw Error(r.message||"Gagal memuat dosen");S.dosen=r.data||[];["p1","p2"].forEach(id=>{let x=$(id);S.dosen.forEach(d=>x.add(new Option(d.nama,d.sourceRow)))})}
function nip(sel,out){let d=S.dosen.find(x=>String(x.sourceRow)===sel.value);$(out).value=d?d.nip:""}
async function load(){status("Memuat data...");let r=await jsonp({});if(r.result!=="success")throw Error(r.message||"Gagal memuat data");S.data=r.data||[];S.loaded=true;let vals=[...new Set(S.data.map(x=>txt(x.angkatan)).filter(Boolean))].sort();$("a").innerHTML='<option value="">Semua angkatan</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join("");status("Data berhasil dimuat")}
function render(){let q=txt($("q").value).toLowerCase(),a=$("a").value;let d=S.data.filter(x=>(!a||x.angkatan===a)&&(!q||[x.nama,x.nim,x.pembimbing1,x.nip1,x.pembimbing2,x.nip2].join(" ").toLowerCase().includes(q)));$("out").innerHTML=d.length?d.map(x=>`<div class="card"><h3>${esc(x.nama)}</h3><div class="muted">NIM: ${esc(x.nim)} | Angkatan: ${esc(x.angkatan)}</div><div class="grid"><p><b>Pembimbing I</b><br>${esc(x.pembimbing1)||"-"}<br><span class="muted">${esc(x.nip1)}</span></p><p><b>Pembimbing II</b><br>${esc(x.pembimbing2)||"-"}<br><span class="muted">${esc(x.nip2)}</span></p></div></div>`).join(""):"<p>Data tidak ditemukan.</p>";status("Total data: "+d.length)}
async function show(){try{if(!S.loaded)await load();render()}catch(e){status(e.message,true)}}
function post(data){return new Promise((ok,no)=>{let id="r"+Date.now()+Math.random().toString(16).slice(2),fr=document.createElement("iframe"),f=document.createElement("form"),to=setTimeout(()=>done(new Error("Penyimpanan timeout")),20000);function done(e,d){clearTimeout(to);window.removeEventListener("message",on);setTimeout(()=>{fr.remove();f.remove()},100);e?no(e):ok(d)}function on(e){let d=e.data;if(d&&d.channel==="psppem"&&d.requestId===id)done(null,d)}window.addEventListener("message",on);fr.name=id;fr.hidden=true;f.method="post";f.action=URL;f.target=id;data.requestId=id;Object.keys(data).forEach(k=>{let i=document.createElement("input");i.type="hidden";i.name=k;i.value=data[k]??"";f.appendChild(i)});document.body.append(fr,f);f.submit()})}
async function save(){let d1=S.dosen.find(x=>String(x.sourceRow)===$("p1").value),d2=S.dosen.find(x=>String(x.sourceRow)===$("p2").value),data={action:"addStudent",nama:txt($("nama").value),nim:txt($("nim").value),angkatan:txt($("angkatan").value),pembimbing1Row:$("p1").value,pembimbing1:d1?.nama||"",nip1:d1?.nip||"",pembimbing2Row:$("p2").value,pembimbing2:d2?.nama||"",nip2:d2?.nip||"",password:$("pass").value};if(!data.nama||!data.nim||!data.angkatan||!data.password)return status("Nama, NIM, angkatan, dan password wajib diisi.",true);try{status("Menyimpan...");let r=await post(data);if(r.result!=="success")throw Error(r.message||"Gagal menyimpan");["nama","nim","angkatan","pass","n1","n2"].forEach(id=>$(id).value="");$("p1").value=$("p2").value="";$("form").hidden=true;S.loaded=false;await load();render();status(r.message)}catch(e){status(e.message,true)}}
$("show").onclick=show;
$("add").onclick=async()=>{try{await loadDosen();$("form").hidden=false;status("")}catch(e){status(e.message,true)}};
$("reset").onclick=()=>{$("q").value="";$("a").value="";$("out").innerHTML="";$("form").hidden=true;status("")};
$("cancel").onclick=()=>{$("form").hidden=true};
$("save").onclick=save;
$("p1").onchange=()=>nip($("p1"),"n1");
$("p2").onchange=()=>nip($("p2"),"n2");
})();